apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-kubernetes-ingress-tcp
  namespace: haproxy-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/name: kubernetes-ingress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
  - name: prometheus
    protocol: TCP
    port: 6060
    targetPort: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-kubernetes-ingress-udp
  namespace: haproxy-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/name: kubernetes-ingress
  ports:
  - name: quic
    protocol: UDP
    port: 443
    targetPort: quic
