server:
  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: gp2
  service:
    type: LoadBalancer
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  ingress:
    enabled: false # Disable as no domain
    annotations: {}
    hosts: []
    tls: []

alertmanager:
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: gp2

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

extraScrapeConfigs: |
  - job_name: 'nginx'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: nginx
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
        action: replace
        target_label: __address__
        regex: (\d+);(.+)
        replacement: $2:$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
