apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
spec:
  finalizers:
  - kubernetes  # This is required to delete the namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus # This label is used to identify the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.45.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-server-config
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-config
  labels:
    app: prometheus
spec:
  data:
    prometheus.yml: |
      global:
        scrape_interval: 15s
      scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
        - targets: ['kubernetes.default.svc:443'] or #['localhost:443'] or #['localhost:9090']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090