name: Deploy to EKS

on:
  push:
    paths:
      - 'kubernetes/nginx/**'
      - '.github/workflows/deploy-nginx.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
     ACTIONS_STEP_DEBUG: true


    permissions:
      id-token: write
      contents: read
      pull-requests: write
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Update Kubeconfig
      run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name demo-eks-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/nginx-deployment.yaml